name: Build ARM user

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        apt --no-install-recommends -y build-dep qemu
        apt install autoconf libtool protobuf-c-compiler
        opam install piqi
        cs /root
        git clone https://github.com/BinaryAnalysisPlatform/bap-frames.git
        git clone git@github.com:BinaryAnalysisPlatform/qemu.git
    - name: Build for ARM
      run: |
        cd qemu
        ./configure --prefix=$HOME --with-tracewrap="/root/bap-frames" --target-list=arm-linux-user
        ninja -C build
        ninja -C build install

